### ISSUE TITLE
Little info about DataSet

### ISSUE THREAD

**Issue by shivSD** [breadbread1984/R3DCNN#10]
Since we don't have dataset, please can you share some information about dataset, 
We see in the .lst file and also in create_Dataset.py

path:./Video_data/class_01/subject13_r0 depth:sk_depth:138:218 color:sk_color:138:218 duo_left:duo_left:161:254 label:1 

sensors = ["color", "depth", "duo_left", "duo_right", "duo_disparity"]

what is this duo_left or duo_right ? or depth (is this a point cloud data ?

**Comment by breadbread1984** [comment]
the lst files and readdata.py come with the dataset. you don't need to care about the structure of the annotation format. you just need to comprehend the sample code in readdata.py. the sensor array specify the alternative input channels.
