### ISSUE TITLE
how to test on cam

### ISSUE THREAD

**Issue by gjghks** [breadbread1984/R3DCNN#3]
Thanks for your achievements.

I downloaded Video_data and the trained C3D model 'action_classifier_model',

and train with command 'python train_r3dcnn.py'

as a training result, train models ware stored in 'gesture_classifier_model' folder.

and then, for a test,

webcam with command 'python ActionRecognition.py'

however, I got some problem.

![image](https://user-images.githubusercontent.com/27722614/46467949-1279cb00-c80a-11e8-8767-1d16343f7dc0.png)

some tensorflow logs showed repeatedly, and slow implement on cam.

In detail, 

ActionRecognition.py, 31 line,

prediction = next(predictions);

A break occurs every time the above code is executed.

My environment
- windows 10
- tensorflow 1.11

please answer about my question.

**Comment by breadbread1984** [comment]
testing online is still a problem to me. even on 1080 ti, the network can only run at 1-2 fps. the low speed would cause a sparse sampled video clip which is different from the training samples. i think this contributes to the low online classification result. you can only verify the model on samples from the dataset offline through evalutation mode of estimator for now. The paper of the algorithm says testing the model on a Titan X takes you 30ms per clip. If that is true, you may need to upgrade to that configuration and test again.

**Comment by geroge-gao** [comment]
@breadbread1984 Thanks for your codes, I had some question  about following code in the  ActionRecognition.py file.
`
features = np.array(self.buf);
features = features.reshape(1,10,8,112,112,3).astype(np.float32)
`
could you tell me what does the number 10 mean?  As I know  8 means the clip's length ，what does the sequence length mean？

**Comment by geroge-gao** [comment]
@breadbread1984 I eval the model on the test set,here is the result
![2018-11-07 20-24-12](https://user-images.githubusercontent.com/11483800/48135419-dbe71280-e2d7-11e8-93e9-a357dd484e01.png)

but when I use the local video file in the test set,it always shows the number 0

![2018-11-07 20-44-31](https://user-images.githubusercontent.com/11483800/48135561-3c764f80-e2d8-11e8-8ec9-0d27ae608d1f.png)
could you tell me what's the problem?

**Comment by breadbread1984** [comment]
you are welcome to give advices and pull request.

**Comment by sainisanjay** [comment]
For both video clip and web cam testing i am getting error like:
```
Traceback (most recent call last):
  File "ActionRecognition.py", line 43, in <module>
    for i in range(0,len(sequence)):
TypeError: object of type 'generator' has no len()

```
any idea whats wrong??

**Comment by sainisanjay** [comment]
@geroge-gao @breadbread1984 For me also it always shows the number 0


![screenshot from 2018-12-26 17-44-53](https://user-images.githubusercontent.com/25616511/50435727-835fe900-0908-11e9-8727-d994f2d4c39b.png)

**Comment by breadbread1984** [comment]
I haven't solve the problem yet. if you have any suggestion, you are welcome to push your patch.

**Comment by sainisanjay** [comment]
@breadbread1984 why all the video clips are falling on below loop:
```
elif len(self.buf) < 80:
	self.buf.append(frame[4:116, 24:136])
	return [0]
```

as this loop return 0 that's why it always showing 0 on frame.

**Comment by breadbread1984** [comment]
ok thanks I will correct it soon

**Comment by world2025** [comment]
@gjghks @sainisanjay @geroge-gao  hello ,did you solve the webcam errors? i met this issues now ? thanks

**Comment by buaa-luzhi** [comment]
@gjghks @sainisanjay @geroge-gao @tkone2018
Hello, when testing a single video file offline, adding an image one frame at a time results in a different output. Do you know why, tahnks!

**Comment by buaa-luzhi** [comment]
@gjghks @sainisanjay @geroge-gao @tkone2018
Hello, when testing a single video file offline, adding an image one frame at a time results in a different output. Do you know why, thanks!

**Comment by buaa-luzhi** [comment]
@gjghks @sainisanjay @geroge-gao @tkone2018
Hello, when testing a single video file offline, adding an image one frame at a time results in a different output. Do you know why, thanks!

**Comment by buaa-luzhi** [comment]
@gjghks @sainisanjay @geroge-gao @tkone2018
Hello, when testing a single video file offline, adding an image one frame at a time results in a different output. Do you know why, thanks!
![fig](https://user-images.githubusercontent.com/28650172/70779146-ea4b0c00-1dbe-11ea-93cd-f2d4017d0816.png)
