### ISSUE TITLE
dataset label

### ISSUE THREAD

**Issue by sunnymoon155** [breadbread1984/R3DCNN#5]
hi author, could you please introduce me how to label the dataset? I mean, I don't understand what the "depth:sk_depth:146:226 color:sk_color:146:226 duo_left:duo_left:170:263 label:1" mean in train and test lst files. Moreover, in data folder, what's the ***_log.txt files used for? Thanks in advance!

**Comment by shajie17** [comment]
@sunnymoon155  hi,do you have nvgestures and have other channels for downloading?
you can run readdata.py to solve your questions

**Comment by breadbread1984** [comment]
thx for answering

**Comment by sunnymoon155** [comment]
@breadbread1984 @shajie17 thanks, I checked readdata.py and found sk_color:146:226 means the gesture is between 146 and 226 frame in color video, is that right? But I didn't find the meaning of **_log.txtL: img00000.png 1440202584613042158. Is that a kind of label?

**Comment by breadbread1984** [comment]
the numbers stand for the beginning and the end of the appearance of a hand gesture in the video clip. the last number is the label for the hand gesture

**Comment by sunnymoon155** [comment]
you mean for "1440202584613042158", "144020258" is the beginning of the appearance of a hand gesture and "461304215" is the end of the appearance of a hand gesture, and "8" is the label? Is that file used for training and testing or we only use the label in nvgesture_train/test_correct_cvpr2016.lst?

**Comment by shajie17** [comment]
@sunnymoon155 I can't find the data folder.
